### ISSUE TITLE
issue bagian login dan signup

### ISSUE THREAD

**Issue by rakhadzaky** [adzkar/Membership-Course#1]
bagian login jika salah pass belum ada pemberitahuannya
jika sign up dengan 2 email yang sama tetap berhasil
pada proses sign up yang bagian no WA, jika yang di input bukan nomor tetap bisa sign up
tidak ada keterangan field yang wajib sehingga saya agak bingung, yang ada hanya keterangan tentang Line dan WA akan digunakan untuk apa XD

cuma itu untuk saat ini, good job

**Comment by adzkar** [comment]
Done @rakhadzaky
